package RentCar;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

public class CatalogoDeFacturas extends javax.swing.JFrame {
    
    DefaultTableModel modelo;
    Conexion cc =new Conexion();
    Connection cn = cc.getConection();
   
    public CatalogoDeFacturas() {
        initComponents();
        this.setLocation(100, 200);
        modelo = new DefaultTableModel();
        modelo.addColumn("Numero");
        modelo.addColumn("Nombre_Cliente");
        modelo.addColumn("Placa");
        modelo.addColumn("Vendedor");
        this.CatalogoFacturas.setModel(modelo);
        llenarTabla();
    }
    
    public void llenarTabla()
    {
        String []Datos = new String[4];
        try {
            Statement st =cn.createStatement();
            ResultSet rs= st.executeQuery("SELECT * FROM factura");
            while (rs.next())
            {
                Datos[0]=rs.getString(1);
                Datos[1]=rs.getString(2);
                Datos[2]=rs.getString(7);
                Datos[3]=rs.getString(8);
                modelo.addRow(Datos);
                
            }
            this.CatalogoFacturas.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(CatalogoDeVehiculos.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnDetalle = new javax.swing.JButton();
        BtnRegresar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CatalogoFacturas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 0));
        setForeground(new java.awt.Color(0, 204, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Catalogo de Facturas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 0, 296, -1));

        BtnDetalle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnDetalle.setText("Detalle");
        BtnDetalle.setBorder(null);
        BtnDetalle.setBorderPainted(false);
        BtnDetalle.setContentAreaFilled(false);
        BtnDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDetalleActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 279, -1, -1));

        BtnRegresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnRegresar.setText("Regresar");
        BtnRegresar.setBorder(null);
        BtnRegresar.setBorderPainted(false);
        BtnRegresar.setContentAreaFilled(false);
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 279, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        CatalogoFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(CatalogoFacturas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void BtnDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDetalleActionPerformed
        int filaseleccionada = CatalogoFacturas.getSelectedRow();
        String placa = CatalogoFacturas.getValueAt(filaseleccionada, 2).toString();
        String numero = CatalogoFacturas.getValueAt(filaseleccionada, 0).toString();
        DetallesFacturas abrir = new DetallesFacturas();
        abrir.llenarTabla( Integer.parseInt(numero), placa);
        abrir.setVisible(true);
    }//GEN-LAST:event_BtnDetalleActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDetalle;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JTable CatalogoFacturas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
