package RentCar;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class FPrincipal extends javax.swing.JFrame {

    Conexion cc =new Conexion();
    Connection cn = cc.getConection();
    
    public FPrincipal() {
        initComponents();
    }
    
    public void Control()
    {
       jMenuAdmin.setVisible(false);
       jNUevoUsuario.setVisible(false);
    }
    public void User(String user)
    {
        lbUsuario.setText(user);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLFondo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuCerrarSe = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenuItem();
        jMenuIngresar = new javax.swing.JMenu();
        jMenuIngresarVehiculo = new javax.swing.JMenuItem();
        jMenuIngresarCliente = new javax.swing.JMenuItem();
        jMenuFacutra = new javax.swing.JMenu();
        jMenuNueva = new javax.swing.JMenuItem();
        jMenuConsultas = new javax.swing.JMenu();
        ConsultaClientes = new javax.swing.JMenuItem();
        jMenuCatalogo = new javax.swing.JMenuItem();
        ConsFactura = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        RepEmpleados = new javax.swing.JMenuItem();
        RepVehiculos = new javax.swing.JMenuItem();
        jMenuAdmin = new javax.swing.JMenu();
        jNUevoUsuario = new javax.swing.JMenuItem();
        CatalogoUsuario = new javax.swing.JMenuItem();
        CambioPass = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AD.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Usuario:");

        lbUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbUsuario.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lbUsuario)
                .addGap(106, 106, 106)
                .addComponent(jLFondo)
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbUsuario))
                .addGap(51, 51, 51))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 544));

        jMenuBar1.setBackground(new java.awt.Color(0, 204, 0));

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setBorder(null);
        jMenu1.setForeground(new java.awt.Color(0, 204, 0));
        jMenu1.setText("Archivo");
        jMenu1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuCerrarSe.setForeground(new java.awt.Color(0, 204, 0));
        jMenuCerrarSe.setText("Cerrar Sesion");
        jMenuCerrarSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCerrarSeActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCerrarSe);

        jMenuSalir.setForeground(new java.awt.Color(0, 204, 0));
        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSalir);

        jMenuBar1.add(jMenu1);

        jMenuIngresar.setBackground(new java.awt.Color(255, 255, 255));
        jMenuIngresar.setBorder(null);
        jMenuIngresar.setForeground(new java.awt.Color(0, 204, 0));
        jMenuIngresar.setText("Ingresar");
        jMenuIngresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIngresarActionPerformed(evt);
            }
        });

        jMenuIngresarVehiculo.setText("Vehiculo");
        jMenuIngresarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIngresarVehiculoActionPerformed(evt);
            }
        });
        jMenuIngresar.add(jMenuIngresarVehiculo);

        jMenuIngresarCliente.setText("Cliente");
        jMenuIngresarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIngresarClienteActionPerformed(evt);
            }
        });
        jMenuIngresar.add(jMenuIngresarCliente);

        jMenuBar1.add(jMenuIngresar);

        jMenuFacutra.setBackground(new java.awt.Color(255, 255, 255));
        jMenuFacutra.setBorder(null);
        jMenuFacutra.setForeground(new java.awt.Color(0, 204, 0));
        jMenuFacutra.setText("Factura");
        jMenuFacutra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuFacutra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFacutraActionPerformed(evt);
            }
        });

        jMenuNueva.setText("Nueva");
        jMenuNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNuevaActionPerformed(evt);
            }
        });
        jMenuFacutra.add(jMenuNueva);

        jMenuBar1.add(jMenuFacutra);

        jMenuConsultas.setBackground(new java.awt.Color(255, 255, 255));
        jMenuConsultas.setBorder(null);
        jMenuConsultas.setForeground(new java.awt.Color(0, 204, 0));
        jMenuConsultas.setText("Consultas");
        jMenuConsultas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultasActionPerformed(evt);
            }
        });

        ConsultaClientes.setText("Clientes");
        ConsultaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaClientesActionPerformed(evt);
            }
        });
        jMenuConsultas.add(ConsultaClientes);

        jMenuCatalogo.setText("Vehiculos");
        jMenuCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCatalogoActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuCatalogo);

        ConsFactura.setText("Facturas");
        ConsFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsFacturaActionPerformed(evt);
            }
        });
        jMenuConsultas.add(ConsFactura);

        jMenuBar1.add(jMenuConsultas);

        jMenu5.setBackground(new java.awt.Color(255, 255, 255));
        jMenu5.setBorder(null);
        jMenu5.setForeground(new java.awt.Color(0, 204, 0));
        jMenu5.setText("Reportes");
        jMenu5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        RepEmpleados.setText("Empleados");
        RepEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepEmpleadosActionPerformed(evt);
            }
        });
        jMenu5.add(RepEmpleados);

        RepVehiculos.setText("Vehiculos");
        RepVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepVehiculosActionPerformed(evt);
            }
        });
        jMenu5.add(RepVehiculos);

        jMenuBar1.add(jMenu5);

        jMenuAdmin.setBackground(new java.awt.Color(255, 255, 255));
        jMenuAdmin.setBorder(null);
        jMenuAdmin.setForeground(new java.awt.Color(0, 204, 0));
        jMenuAdmin.setText("Administrador");
        jMenuAdmin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jNUevoUsuario.setText("Nuevo Usuario");
        jNUevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNUevoUsuarioActionPerformed(evt);
            }
        });
        jMenuAdmin.add(jNUevoUsuario);

        CatalogoUsuario.setText("Catalogo Usuarios");
        CatalogoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatalogoUsuarioActionPerformed(evt);
            }
        });
        jMenuAdmin.add(CatalogoUsuario);

        CambioPass.setText("Cambio pass");
        CambioPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambioPassActionPerformed(evt);
            }
        });
        jMenuAdmin.add(CambioPass);

        jMenuBar1.add(jMenuAdmin);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCerrarSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCerrarSeActionPerformed

        Login principal= new Login();
        principal.setVisible(true);
        principal.pack();
        this.dispose();
    }//GEN-LAST:event_jMenuCerrarSeActionPerformed

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
       

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuIngresarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIngresarVehiculoActionPerformed
        
        FNuevoVehiculo iv= new FNuevoVehiculo();
       
        iv.setVisible(true);
    }//GEN-LAST:event_jMenuIngresarVehiculoActionPerformed

    private void jMenuIngresarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIngresarClienteActionPerformed
       FNuevoCliente ic= new FNuevoCliente();
       ic.setVisible(true);
    }//GEN-LAST:event_jMenuIngresarClienteActionPerformed

    private void jMenuIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIngresarActionPerformed
    

    }//GEN-LAST:event_jMenuIngresarActionPerformed

    private void jMenuNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNuevaActionPerformed
        FAlquiler ic = new FAlquiler();
        ic.setVisible(true);
        ic.fUser(lbUsuario.getText());
        
    }//GEN-LAST:event_jMenuNuevaActionPerformed

    private void jMenuFacutraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFacutraActionPerformed
        
    }//GEN-LAST:event_jMenuFacutraActionPerformed

    private void ConsultaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaClientesActionPerformed
        CatalogoDeClientes abrir =new CatalogoDeClientes();
        abrir.setVisible(true);
        
    }//GEN-LAST:event_ConsultaClientesActionPerformed

    private void jMenuCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCatalogoActionPerformed
        CatalogoDeVehiculos abrir =new CatalogoDeVehiculos();
        abrir.setVisible(true);
       
    }//GEN-LAST:event_jMenuCatalogoActionPerformed

    private void ConsFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsFacturaActionPerformed
        CatalogoDeFacturas abrir =new CatalogoDeFacturas();
        abrir.setVisible(true);
    }//GEN-LAST:event_ConsFacturaActionPerformed

    private void jMenuConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultasActionPerformed
        
    }//GEN-LAST:event_jMenuConsultasActionPerformed

    private void RepEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepEmpleadosActionPerformed
        ReporteEmpleado abrir =new ReporteEmpleado();
        abrir.setVisible(true);

        
    }//GEN-LAST:event_RepEmpleadosActionPerformed

    private void RepVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepVehiculosActionPerformed
        ReporteVehiculo abrir =new ReporteVehiculo();
        abrir.setVisible(true);
       
    }//GEN-LAST:event_RepVehiculosActionPerformed

    private void jNUevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNUevoUsuarioActionPerformed
        FnuevoUsuario abrir =new FnuevoUsuario();
        abrir.setVisible(true);
    }//GEN-LAST:event_jNUevoUsuarioActionPerformed

    private void CatalogoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatalogoUsuarioActionPerformed
       CatalogoUsuarios abrir =new CatalogoUsuarios();
       abrir.setVisible(true);
    }//GEN-LAST:event_CatalogoUsuarioActionPerformed

    private void CambioPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambioPassActionPerformed
       FCambioPass abrir =new FCambioPass();
       abrir.setVisible(true);
    }//GEN-LAST:event_CambioPassActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CambioPass;
    private javax.swing.JMenuItem CatalogoUsuario;
    private javax.swing.JMenuItem ConsFactura;
    private javax.swing.JMenuItem ConsultaClientes;
    private javax.swing.JMenuItem RepEmpleados;
    private javax.swing.JMenuItem RepVehiculos;
    private javax.swing.JLabel jLFondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenuAdmin;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCatalogo;
    private javax.swing.JMenuItem jMenuCerrarSe;
    private javax.swing.JMenu jMenuConsultas;
    private javax.swing.JMenu jMenuFacutra;
    private javax.swing.JMenu jMenuIngresar;
    private javax.swing.JMenuItem jMenuIngresarCliente;
    private javax.swing.JMenuItem jMenuIngresarVehiculo;
    private javax.swing.JMenuItem jMenuNueva;
    private javax.swing.JMenuItem jMenuSalir;
    private javax.swing.JMenuItem jNUevoUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbUsuario;
    // End of variables declaration//GEN-END:variables
}
