
package RentCar;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class ReporteVehiculo extends javax.swing.JFrame {

    DefaultTableModel modelo;
    Conexion cc =new Conexion();
    Connection cn = cc.getConection();
    public ReporteVehiculo() {
        initComponents();
        this.setLocation(200, 100);
        modelo = new DefaultTableModel();
        modelo.addColumn("Placa");
        modelo.addColumn("Marca");
        modelo.addColumn("Modelo");
        modelo.addColumn("Estado");
        this.ReporteVehiculo.setModel(modelo);
        llenarTabla();
    }
    public void llenarTabla()
    {
        String []Datos = new String[4];
        try {
            Statement st =cn.createStatement();
            ResultSet rs= st.executeQuery("SELECT * FROM vehiculos"
                    + " WHERE Estado ='Alquilado'");
            while (rs.next())
            {
                Datos[0]=rs.getString(1);
                Datos[1]=rs.getString(2);
                Datos[2]=rs.getString(3);
                Datos[3]=rs.getString(8);
                modelo.addRow(Datos);
                
            }
            this.ReporteVehiculo.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(CatalogoDeVehiculos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void Cambio(String placa)
    {

        String sql = "UPDATE vehiculos SET Estado ='Disponible'"
                + " WHERE Placa='" + placa + "'";
        try {
            PreparedStatement st = cn.prepareStatement(sql);
            st.executeUpdate();
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReporteVehiculo = new javax.swing.JTable();
        jBtnRecibir = new javax.swing.JButton();
        jBtnRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        ReporteVehiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(ReporteVehiculo);

        jBtnRecibir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnRecibir.setText("Recibir Vehiculo");
        jBtnRecibir.setBorder(null);
        jBtnRecibir.setBorderPainted(false);
        jBtnRecibir.setContentAreaFilled(false);
        jBtnRecibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRecibirActionPerformed(evt);
            }
        });

        jBtnRegresar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnRegresar.setText("Regresar");
        jBtnRegresar.setBorder(null);
        jBtnRegresar.setBorderPainted(false);
        jBtnRegresar.setContentAreaFilled(false);
        jBtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegresarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Reporte De Vehiculos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jBtnRecibir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnRegresar)
                .addGap(95, 95, 95))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(102, 102, 102))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnRecibir)
                    .addComponent(jBtnRegresar))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegresarActionPerformed
      
        dispose();
    }//GEN-LAST:event_jBtnRegresarActionPerformed

    private void jBtnRecibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRecibirActionPerformed
        int filaseleccionada = ReporteVehiculo.getSelectedRow();
        String placa = ReporteVehiculo.getValueAt(filaseleccionada, 0).toString();
        Cambio(placa);
    }//GEN-LAST:event_jBtnRecibirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ReporteVehiculo;
    private javax.swing.JButton jBtnRecibir;
    private javax.swing.JButton jBtnRegresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
